# Site settings
title: Zhéyuán Chén
description: "Zhéyuán Chén's homepage"
baseurl: ""
url: "https://czheo.github.io"

# Build settings
permalink: pretty

collections:
  category:
    output: true

include: [".well-known/brave-rewards-verification.txt"]
